name: firemodel-env
channels:
  - conda-forge
dependencies:
  - python=3.12  # or your preferred version
  - pandas
  - matplotlib
  - geopandas
  - contextily
  - ipywidgets
  - notebook
  - jupyterlab
  - ipykernel
  - xyzservices  # required by contextily for basemaps
  - pip
  - pip:
      - ipywidgets  # ensure ipywidgets works fully in notebook
